package com.mycompany.practice_task_3;
// Generated 02.07.2016 16:47:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name="country"
    ,catalog="practice_task_2"
)
public class Country  implements java.io.Serializable {


     private String name;
     private Integer population;
     private Integer area;
     private String capital;

    public Country() {
    }

	
    public Country(String name) {
        this.name = name;
    }
    public Country(String name, Integer population, Integer area, String capital) {
       this.name = name;
       this.population = population;
       this.area = area;
       this.capital = capital;
    }
   
     @Id 

    
    @Column(name="Name", unique=true, nullable=false, length=40)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Population")
    public Integer getPopulation() {
        return this.population;
    }
    
    public void setPopulation(Integer population) {
        this.population = population;
    }

    
    @Column(name="Area")
    public Integer getArea() {
        return this.area;
    }
    
    public void setArea(Integer area) {
        this.area = area;
    }

    
    @Column(name="Capital", length=40)
    public String getCapital() {
        return this.capital;
    }
    
    public void setCapital(String capital) {
        this.capital = capital;
    }




}


