package com.mycompany.practice_task_3;
// Generated 02.07.2016 16:47:59 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Festival generated by hbm2java
 */
@Entity
@Table(name="festival"
    ,catalog="practice_task_2"
)
public class Festival  implements java.io.Serializable {


     private FestivalId id;
     private Integer places;
     private String country;
     private String organizer;

    public Festival() {
    }

	
    public Festival(FestivalId id) {
        this.id = id;
    }
    public Festival(FestivalId id, Integer places, String country, String organizer) {
       this.id = id;
       this.places = places;
       this.country = country;
       this.organizer = organizer;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="name", column=@Column(name="Name", nullable=false, length=40) ), 
        @AttributeOverride(name="city", column=@Column(name="City", nullable=false, length=40) ) } )
    public FestivalId getId() {
        return this.id;
    }
    
    public void setId(FestivalId id) {
        this.id = id;
    }

    
    @Column(name="Places")
    public Integer getPlaces() {
        return this.places;
    }
    
    public void setPlaces(Integer places) {
        this.places = places;
    }

    
    @Column(name="Country", length=40)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="Organizer", length=40)
    public String getOrganizer() {
        return this.organizer;
    }
    
    public void setOrganizer(String organizer) {
        this.organizer = organizer;
    }




}


