package com.mycompany.practice_task_3;
// Generated 02.07.2016 16:47:59 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Festivalorganizer generated by hbm2java
 */
@Entity
@Table(name="festivalorganizer"
    ,catalog="practice_task_2"
)
public class Festivalorganizer  implements java.io.Serializable {


     private FestivalorganizerId id;

    public Festivalorganizer() {
    }

    public Festivalorganizer(FestivalorganizerId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="name", column=@Column(name="Name", nullable=false, length=40) ), 
        @AttributeOverride(name="accreditationCountry", column=@Column(name="AccreditationCountry", nullable=false, length=40) ) } )
    public FestivalorganizerId getId() {
        return this.id;
    }
    
    public void setId(FestivalorganizerId id) {
        this.id = id;
    }




}


