package com.mycompany.maven;
// Generated 07.07.2016 16:47:39 by Hibernate Tools 4.3.1



/**
 * Country generated by hbm2java
 */
public class Country  implements java.io.Serializable {


     private String name;
     private City city;
     private Integer population;
     private Integer area;

    public Country() {
    }

	
    public Country(String name) {
        this.name = name;
    }
    public Country(String name, City city, Integer population, Integer area) {
       this.name = name;
       this.city = city;
       this.population = population;
       this.area = area;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public Integer getPopulation() {
        return this.population;
    }
    
    public void setPopulation(Integer population) {
        this.population = population;
    }
    public Integer getArea() {
        return this.area;
    }
    
    public void setArea(Integer area) {
        this.area = area;
    }




}


