package com.mycompany.maven;
// Generated 07.07.2016 16:47:39 by Hibernate Tools 4.3.1



/**
 * Festivalorganizer generated by hbm2java
 */
public class Festivalorganizer  implements java.io.Serializable {


     private FestivalorganizerId id;

    public Festivalorganizer() {
    }

    public Festivalorganizer(FestivalorganizerId id) {
       this.id = id;
    }
   
    public FestivalorganizerId getId() {
        return this.id;
    }
    
    public void setId(FestivalorganizerId id) {
        this.id = id;
    }




}


