package com.mycompany.maven;
// Generated 07.07.2016 16:47:39 by Hibernate Tools 4.3.1



/**
 * Festival generated by hbm2java
 */
public class Festival  implements java.io.Serializable {


     private String name;
     private String city;
     private Integer places;
     private String country;
     private String organizer;

    public Festival() {
    }

	
    public Festival(String name) {
        this.name = name;
    }
    public Festival(String name, String city, Integer places, String country, String organizer) {
       this.name = name;
       this.city = city;
       this.places = places;
       this.country = country;
       this.organizer = organizer;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Integer getPlaces() {
        return this.places;
    }
    
    public void setPlaces(Integer places) {
        this.places = places;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getOrganizer() {
        return this.organizer;
    }
    
    public void setOrganizer(String organizer) {
        this.organizer = organizer;
    }




}


