package database;
// Generated 13.07.2016 12:33:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AnswersforOqId generated by hbm2java
 */
@Embeddable
public class AnswersforOqId  implements java.io.Serializable {


     private String itemname;
     private String answer;

    public AnswersforOqId() {
    }

    public AnswersforOqId(String itemname, String answer) {
       this.itemname = itemname;
       this.answer = answer;
    }
   


    @Column(name="itemname", nullable=false, length=64)
    public String getItemname() {
        return this.itemname;
    }
    
    public void setItemname(String itemname) {
        this.itemname = itemname;
    }


    @Column(name="answer", nullable=false, length=64)
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AnswersforOqId) ) return false;
		 AnswersforOqId castOther = ( AnswersforOqId ) other; 
         
		 return ( (this.getItemname()==castOther.getItemname()) || ( this.getItemname()!=null && castOther.getItemname()!=null && this.getItemname().equals(castOther.getItemname()) ) )
 && ( (this.getAnswer()==castOther.getAnswer()) || ( this.getAnswer()!=null && castOther.getAnswer()!=null && this.getAnswer().equals(castOther.getAnswer()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getItemname() == null ? 0 : this.getItemname().hashCode() );
         result = 37 * result + ( getAnswer() == null ? 0 : this.getAnswer().hashCode() );
         return result;
   }   


}


