package database;
// Generated 15.07.2016 9:53:11 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AnswersId generated by hbm2java
 */
@Embeddable
public class AnswersId  implements java.io.Serializable {


     private int iditem;
     private String answer;

    public AnswersId() {
    }

    public AnswersId(int iditem, String answer) {
       this.iditem = iditem;
       this.answer = answer;
    }
   


    @Column(name="iditem", nullable=false)
    public int getIditem() {
        return this.iditem;
    }
    
    public void setIditem(int iditem) {
        this.iditem = iditem;
    }


    @Column(name="answer", nullable=false, length=64)
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AnswersId) ) return false;
		 AnswersId castOther = ( AnswersId ) other; 
         
		 return (this.getIditem()==castOther.getIditem())
 && ( (this.getAnswer()==castOther.getAnswer()) || ( this.getAnswer()!=null && castOther.getAnswer()!=null && this.getAnswer().equals(castOther.getAnswer()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIditem();
         result = 37 * result + ( getAnswer() == null ? 0 : this.getAnswer().hashCode() );
         return result;
   }   


}


