package database;
// Generated 13.07.2016 12:33:59 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AnswersforOq generated by hbm2java
 */
@Entity
@Table(name="AnswersforOQ"
    ,catalog="EventDB"
)
public class AnswersforOq  implements java.io.Serializable {


     private AnswersforOqId id;
     private OptionalQuestions questions;

    public AnswersforOq() {
    }

    public AnswersforOq(AnswersforOqId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="itemname", column=@Column(name="itemname", nullable=false, length=64) ), 
        @AttributeOverride(name="answer", column=@Column(name="answer", nullable=false, length=64) ) } )
    public AnswersforOqId getId() {
        return this.id;
    }
    
    public void setId(AnswersforOqId id) {
        this.id = id;
    }
    
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="iditem", nullable=false, insertable=false, updatable=false)
    public OptionalQuestions getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(OptionalQuestions questions) {
        this.questions = questions;
    }



}


