package database;
// Generated 15.07.2016 9:53:11 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Blobs generated by hbm2java
 */
@Entity
@Table(name="blobs"
    ,catalog="practice_project"
)
public class Blobs  implements java.io.Serializable {


     private BlobsId id;
     private Questions questions;
     private Users users;
     private byte[] value;

    public Blobs() {
    }

	
    public Blobs(BlobsId id, Questions questions, Users users) {
        this.id = id;
        this.questions = questions;
        this.users = users;
    }
    public Blobs(BlobsId id, Questions questions, Users users, byte[] value) {
       this.id = id;
       this.questions = questions;
       this.users = users;
       this.value = value;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="iduser", nullable=false) ), 
        @AttributeOverride(name="iditem", column=@Column(name="iditem", nullable=false) ), 
        @AttributeOverride(name="idevent", column=@Column(name="idevent", nullable=false) ) } )
    public BlobsId getId() {
        return this.id;
    }
    
    public void setId(BlobsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iditem", nullable=false, insertable=false, updatable=false)
    public Questions getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Questions questions) {
        this.questions = questions;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="iduser", referencedColumnName="iduser", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="idevent", referencedColumnName="idevent", nullable=false, insertable=false, updatable=false) } )
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="value")
    public byte[] getValue() {
        return this.value;
    }
    
    public void setValue(byte[] value) {
        this.value = value;
    }




}


