package database;
// Generated 15.07.2016 9:53:11 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dates generated by hbm2java
 */
@Entity
@Table(name="dates"
    ,catalog="practice_project"
)
public class Dates  implements java.io.Serializable {


     private DatesId id;
     private Questions questions;
     private Users users;
     private Date value;

    public Dates() {
    }

    public Dates(DatesId id, Questions questions, Users users, Date value) {
       this.id = id;
       this.questions = questions;
       this.users = users;
       this.value = value;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="iduser", nullable=false) ), 
        @AttributeOverride(name="iditem", column=@Column(name="iditem", nullable=false) ), 
        @AttributeOverride(name="idevent", column=@Column(name="idevent", nullable=false) ) } )
    public DatesId getId() {
        return this.id;
    }
    
    public void setId(DatesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iditem", nullable=false, insertable=false, updatable=false)
    public Questions getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Questions questions) {
        this.questions = questions;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="iduser", referencedColumnName="iduser", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="idevent", referencedColumnName="idevent", nullable=false, insertable=false, updatable=false) } )
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="value", nullable=false, length=19)
    public Date getValue() {
        return this.value;
    }
    
    public void setValue(Date value) {
        this.value = value;
    }




}


