package database;
// Generated 13.07.2016 12:33:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OptionalQuestions generated by hbm2java
 */
@Entity
@Table(name="OptionalQuestions"
    ,catalog="EventDB"
)
public class OptionalQuestions  implements java.io.Serializable {


     private String itemname;
     private String tag;
     private String type;
     private String description;
     private Set<AnswersforOq> answerses = new HashSet<AnswersforOq>(0);


    public OptionalQuestions() {
    }

	
    public OptionalQuestions(String itemname) {
        this.itemname = itemname;
    }
    public OptionalQuestions(String itemname, String tag, String type, String description) {
       this.itemname = itemname;
       this.tag = tag;
       this.type = type;
       this.description = description;
    }
   
     @Id 

    
    @Column(name="itemname", unique=true, nullable=false, length=64)
    public String getItemname() {
        return this.itemname;
    }
    
    public void setItemname(String itemname) {
        this.itemname = itemname;
    }

    
    @Column(name="tag", length=8)
    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }

    
    @Column(name="type", length=8)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="description", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(fetch=FetchType.EAGER, mappedBy="optionalquestions")
    public Set<AnswersforOq> getAnswerses() {
        return this.answerses;
    }
    
    public void setAnswerses(Set<AnswersforOq> answerses) {
        this.answerses = answerses;
    }
    

}


