package database;
// Generated 15.07.2016 9:53:11 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Strings generated by hbm2java
 */
@Entity
@Table(name="strings"
    ,catalog="practice_project"
)
public class Strings  implements java.io.Serializable {


     private StringsId id;
     private Questions questions;
     private Users users;

    public Strings() {
    }

    public Strings(StringsId id, Questions questions, Users users) {
       this.id = id;
       this.questions = questions;
       this.users = users;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="iduser", nullable=false) ), 
        @AttributeOverride(name="iditem", column=@Column(name="iditem", nullable=false) ), 
        @AttributeOverride(name="idevent", column=@Column(name="idevent", nullable=false) ), 
        @AttributeOverride(name="value", column=@Column(name="value", nullable=false, length=256) ) } )
    public StringsId getId() {
        return this.id;
    }
    
    public void setId(StringsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iditem", nullable=false, insertable=false, updatable=false)
    public Questions getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Questions questions) {
        this.questions = questions;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="iduser", referencedColumnName="iduser", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="idevent", referencedColumnName="idevent", nullable=false, insertable=false, updatable=false) } )
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


