package database;
// Generated 15.07.2016 9:53:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="practice_project"
    , uniqueConstraints = @UniqueConstraint(columnNames={"idevent", "surname"}) 
)
public class Users  implements java.io.Serializable {


     private UsersId id;
     private Events events;
     private String surname;
     private String name;
     private Set<Numbers> numberses = new HashSet<Numbers>(0);
     private Set<Blobs> blobses = new HashSet<Blobs>(0);
     private Set<Strings> stringses = new HashSet<Strings>(0);
     private Set<Dates> dateses = new HashSet<Dates>(0);

    public Users() {
    }

	
    public Users(UsersId id, Events events) {
        this.id = id;
        this.events = events;
    }
    public Users(UsersId id, Events events, String surname, String name, Set<Numbers> numberses, Set<Blobs> blobses, Set<Strings> stringses, Set<Dates> dateses) {
       this.id = id;
       this.events = events;
       this.surname = surname;
       this.name = name;
       this.numberses = numberses;
       this.blobses = blobses;
       this.stringses = stringses;
       this.dateses = dateses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iduser", column=@Column(name="iduser", nullable=false) ), 
        @AttributeOverride(name="idevent", column=@Column(name="idevent", nullable=false) ) } )
    public UsersId getId() {
        return this.id;
    }
    
    public void setId(UsersId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idevent", nullable=false, insertable=false, updatable=false)
    public Events getEvents() {
        return this.events;
    }
    
    public void setEvents(Events events) {
        this.events = events;
    }

    
    @Column(name="surname", length=64)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="name", length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<Numbers> getNumberses() {
        return this.numberses;
    }
    
    public void setNumberses(Set<Numbers> numberses) {
        this.numberses = numberses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<Blobs> getBlobses() {
        return this.blobses;
    }
    
    public void setBlobses(Set<Blobs> blobses) {
        this.blobses = blobses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<Strings> getStringses() {
        return this.stringses;
    }
    
    public void setStringses(Set<Strings> stringses) {
        this.stringses = stringses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<Dates> getDateses() {
        return this.dateses;
    }
    
    public void setDateses(Set<Dates> dateses) {
        this.dateses = dateses;
    }




}


